version: '2'
services:
    
    web:
        build: .
        command: python -u main_app.py
        volumes:
            - .:/code
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        image: mongo:3.0.2
        ports:
            - "27017:27017"
