version: '2'
services:
    web:
        build: .
        command: python -u main_app.py
        volumes:
            - .:/code
        ports:
            - "5000:5000"
        links:
            - db
        environment:
            - DB_PORT_27017_TCP_ADDR=db
    db:
        image: mongo
        ports:
            - "27017:27017"
        command: "--smallfiles --logpath=/dev/null"
